version: '3.7'

services:
    db:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: example
    backend:
        container_name: lovelocalapi
        build:
            context: ./backend
            dockerfile: Dockerfile
        # We run a pip install to catch cases where requirements were added but a Docker build hasn't run yet
        command: bash -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
        working_dir: /usr/local/site/
        volumes:
        - ./backend/:/usr/local/site/
        - ../certificates/private_keys.py:/usr/local/site/carebackend/private_keys.py
        ports:
        - 8000:8000
        env_file:
        - ./.env.dev
        depends_on:
            - db
    web-app:
        container_name: lovelocalweb
        build:
          context: ./client
          dockerfile: Dockerfile
        volumes:
          - /app/node_modules
          - ./client:/app
        ports:
          - '3000:3000'
        restart: on-failure
        # tty: true
        depends_on: 
            - backend
    frontend:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - backend
        volumes:
        - ./nginx/build/:/usr/local/build/
        - ../certificates/letsencrypt/:/etc/letsencrypt/
        - ./backend/carebackend/django-static/:/usr/local/django-static/
        - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
        - ../certificates/nginx_auth:/etc/nginx/nginx_auth

    frontend:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - backend
        volumes:
        - ./nginx/build/:/usr/local/build/
        - ../certificates/letsencrypt/:/etc/letsencrypt/
        - ./backend/carebackend/django-static/:/usr/local/django-static/
        - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
        - ../certificates/nginx_auth:/etc/nginx/nginx_auth

volumes:
    pgdata: