runtime: custom
#python
env: flex
entrypoint: gunicorn -b :$PORT mysite.wsgi

beta_settings:
    cloud_sql_instances: "<your-db-instance-identifying-string>"

runtime_config:
  python_version: 3

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static/
# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto

env_variables:
  DB_USER: "postgres"
  DB_NAME: "postgres"
  DB_PSWD: "h@tchw@ay$"
  DB_HOST: "cloudsql/lovelocals-272900:us-central1:lovelocals/.s.PGSQL.5432"
  DJANGO_ALLOWED_HOSTS: "*"
  SECRET_KEY: "H@tchw@ay$"
  DJANGO_SETTINGS_MODULE: "carebackend.settings"