runtime: custom

# the PROJECT-DIRECTORY is the one with settings.py and wsgi.py
entrypoint: gunicorn -b :$PORT carebackend.wsgi # specific to a GUnicorn HTTP server deployment
env: flex # for Google Cloud Flexible App Engine

beta_settings:
    cloud_sql_instances: "lovelocals-272900:us-central1:lovelocals"

runtime_config:
  python_version: 3

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static
  secure: always

# - url: /static/(.*)
#   static_files: client/build/static/\1
#   upload: client/build/static/.*
#   expiration: '100d'
#   secure: always

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto

env_variables:
  DB_USER: "postgres"
  DB_NAME: "postgres"
  DB_PSWD: "h@tchw@ay$"
  DB_HOST: "cloudsql/lovelocals-272900:us-central1:lovelocals/.s.PGSQL.5432"
  DJANGO_ALLOWED_HOSTS: "*"
  SECRET_KEY: "H@tchw@ay$"
  DJANGO_SETTINGS_MODULE: "carebackend.settings"
#   STATIC_URL: "https://storage.googleapis.com/lovelocals-272900.appspot.com/"
  DEBUG: "False"
