# Generated by Django 3.0.4 on 2020-03-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='donation_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='email_contact',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='gift_card_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='image_attribution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='num_ratings',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='place_types',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='place_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='takeout_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='user_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
