# Generated by Django 3.0.4 on 2020-04-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20200328_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='address',
        ),
        migrations.RemoveField(
            model_name='place',
            name='donation_url',
        ),
        migrations.RemoveField(
            model_name='place',
            name='email_contact',
        ),
        migrations.RemoveField(
            model_name='place',
            name='gift_card_url',
        ),
        migrations.RemoveField(
            model_name='place',
            name='image',
        ),
        migrations.RemoveField(
            model_name='place',
            name='image_attribution',
        ),
        migrations.RemoveField(
            model_name='place',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='place',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='place',
            name='num_ratings',
        ),
        migrations.RemoveField(
            model_name='place',
            name='place_types',
        ),
        migrations.RemoveField(
            model_name='place',
            name='place_url',
        ),
        migrations.RemoveField(
            model_name='place',
            name='takeout_url',
        ),
        migrations.RemoveField(
            model_name='place',
            name='user_rating',
        ),
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='place',
            name='country',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='place',
            name='giftcard_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='phone',
            field=models.TextField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='place',
            name='postal_code',
            field=models.TextField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='place',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='province',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='place',
            name='street_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='place',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='place',
            name='yelp_id',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='image_url',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
