# Generated by Django 3.0.4 on 2020-04-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20200409_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='contact',
            field=models.TextField(blank=True),
        ),
    ]
