# Generated by Django 3.0.4 on 2020-04-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_place_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.TextField(db_index=True),
        ),
    ]
