# Generated by Django 3.0.4 on 2020-04-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20200409_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='ig_handle',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='shop_url',
            field=models.URLField(blank=True),
        ),
    ]
